### ISSUE TITLE
Instructions for testing commands with MockBukkit

### ISSUE THREAD

**Issue by JorelAli** [CommandAPI/CommandAPI#356]
### Description

Instructions for testing the CommandAPI with MockBukkit. Some worked examples, how to set up a project for testing, inclusion of the plugin-test dependency and support for plugins that are shading the CommandAPI are all stuff that would need to be done.

**Comment by tatanpoker09** [comment]
Is there already a plan to incorporate these instructions onto the documentation? I was looking into it myself but I'm having trouble with nms. I am currently trying to copy a little from the plugin-test folder, but a detailed tutorial to avoid having unnecessary bloat would be appreciated

**Comment by JorelAli** [comment]
> Is there already a plan to incorporate these instructions onto the documentation? I was looking into it myself but I'm having trouble with nms. I am currently trying to copy a little from the plugin-test folder, but a detailed tutorial to avoid having unnecessary bloat would be appreciated

Yes! When a suitable framework structure has been made and we're ready to release the public testing setup for CommandAPI commands, we'll add it to the main documentation :)

**Comment by fhnaumann** [comment]
Is there an estimate when this will be available?

**Comment by willkroboth** [comment]
For those following this issue, #575 has been merged to the development branch. Command tests with MockBukkit are now possible using the `commandapi-bukkit-test-toolkit:9.6.2-SNAPSHOT` dependency. Instructions for how to access the development snapshot can be found on the [CommandAPI Discord](https://discord.com/channels/745416925924032523/1003382482944671804/1300605343654481921).
