### ISSUE TITLE
1.21.4

### ISSUE THREAD

**Issue by quiquelhappy** [CommandAPI/CommandAPI#617]
### CommandAPI version

Latest

### Minecraft version

1.21.3

### Are you shading the CommandAPI?

Yes

### What I did

Use

### What actually happened

No workey

### What should have happened

Workey

**Comment by MC-XiaoHei** [comment]
What are you talking about? Do you mean requesting support for 1.21.4?

**Comment by quiquelhappy** [comment]
yee

**Comment by JorelAli** [comment]
CommandAPI 9.7.0 now supports Minecraft 1.21.4.
